/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
#define SWIG_NOINCLUDE

#ifdef __cplusplus
template<class T> class SwigValueWrapper {
    T *tt;
public:
    SwigValueWrapper() : tt(0) { }
    SwigValueWrapper(const SwigValueWrapper<T>& rhs) : tt(new T(*rhs.tt)) { }
    SwigValueWrapper(const T& t) : tt(new T(t)) { }
    ~SwigValueWrapper() { delete tt; } 
    SwigValueWrapper& operator=(const T& t) { delete tt; tt = new T(t); return *this; }
    operator T&() const { return *tt; }
    T *operator&() { return tt; }
private:
    SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
};                                                    
#endif


#include "Python.h"

/*************************************************************** -*- c -*-
 * python/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Python_TypeRegister
#define SWIG_TypeCheck       SWIG_Python_TypeCheck
#define SWIG_TypeCast        SWIG_Python_TypeCast
#define SWIG_TypeDynamicCast SWIG_Python_TypeDynamicCast
#define SWIG_TypeName        SWIG_Python_TypeName
#define SWIG_TypeQuery       SWIG_Python_TypeQuery
#define SWIG_TypeClientData  SWIG_Python_TypeClientData
#define SWIG_PackData        SWIG_Python_PackData 
#define SWIG_UnpackData      SWIG_Python_UnpackData 


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Python_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Python_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Python_MustGetPtr(p, type, argnum, flags)

/* Python-specific SWIG API */
#define SWIG_newvarlink() \
  SWIG_Python_newvarlink()
#define SWIG_addvarlink(p, name, get_attr, set_attr) \
  SWIG_Python_addvarlink(p, name, get_attr, set_attr)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Python_ConvertPacked(obj, ptr, sz, ty, flags)
#define SWIG_NewPackedObj(ptr, sz, type) \
  SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_InstallConstants(d, constants) \
  SWIG_Python_InstallConstants(d, constants)

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(int)               SWIG_Python_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPointerObj(void *, swig_type_info *,int own);
SWIGIMPORT(void *)            SWIG_Python_MustGetPtr(PyObject *, swig_type_info *, int, int);
SWIGIMPORT(PyObject *)        SWIG_Python_newvarlink(void);
SWIGIMPORT(void)              SWIG_Python_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGIMPORT(int)               SWIG_Python_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPackedObj(void *, int sz, swig_type_info *);
SWIGIMPORT(void)              SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",              /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_Python_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_Python_addvarlink(PyObject *p, char *name, PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
    PyObject *zero = PyInt_FromLong(0);
    PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
    Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a pointer value, signal an exception on a type mismatch */
SWIGRUNTIME(void *)
SWIG_Python_MustGetPtr(PyObject *obj, swig_type_info *ty, int argnum, int flags) {
  void *result;
  SWIG_Python_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_Python_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
        PyObject *n = PyInt_FromLong(1);
        PyObject_SetAttrString(inst,(char*)"thisown",n);
        Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_Python_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { PyErr_SetString(PyExc_RuntimeError, (char *) msg ); goto fail; } else

#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_p_CvCapture swig_types[0] 
#define  SWIGTYPE_p_CvCapture swig_types[1] 
#define  SWIGTYPE_p_IplImage swig_types[2] 
#define  SWIGTYPE_p_CvvImage swig_types[3] 
#define  SWIGTYPE_CvMouseCallback swig_types[4] 
#define  SWIGTYPE_CvTrackbarCallback swig_types[5] 
#define  SWIGTYPE_p_void swig_types[6] 
#define  SWIGTYPE_p_CvSize swig_types[7] 
#define  SWIGTYPE_p_p_char swig_types[8] 
#define  SWIGTYPE_p_p_CvVideoWriter swig_types[9] 
#define  SWIGTYPE_p_CvVideoWriter swig_types[10] 
#define  SWIGTYPE_p_CvRect swig_types[11] 
#define  SWIGTYPE_p_CvArr swig_types[12] 
#define  SWIGTYPE_p_int swig_types[13] 
static swig_type_info *swig_types[15];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _highgui.so
  ------------------------------------------------*/
#define SWIG_init    init_highgui

#define SWIG_name    "_highgui"

#include "highgui.h"

extern "C" int cvInitSystem(int,char **);
extern "C" int cvNamedWindow(char const *,int);
extern "C" void cvShowImage(char const *,CvArr const *);
extern "C" void cvResizeWindow(char const *,int,int);
extern "C" void cvMoveWindow(char const *,int,int);
extern "C" void cvDestroyWindow(char const *);
extern "C" void cvDestroyAllWindows(void);
extern "C" void *cvGetWindowHandle(char const *);
extern "C" char const *cvGetWindowName(void *);
extern "C" int cvCreateTrackbar(char const *,char const *,int *,int,CvTrackbarCallback);
extern "C" int cvGetTrackbarPos(char const *,char const *);
extern "C" void cvSetTrackbarPos(char const *,char const *,int);
extern "C" void cvSetMouseCallback(char const *,CvMouseCallback);
extern "C" IplImage *cvLoadImage(char const *,int);
extern "C" int cvSaveImage(char const *,CvArr const *);
extern "C" void cvConvertImage(CvArr const *,CvArr *,int);
extern "C" int cvWaitKey(int);
extern "C" CvCapture *cvCaptureFromFile(char const *);
extern "C" CvCapture *cvCaptureFromCAM(int);
extern "C" int cvGrabFrame(CvCapture *);
extern "C" IplImage *cvRetrieveFrame(CvCapture *);
extern "C" IplImage *cvQueryFrame(CvCapture *);
extern "C" void cvReleaseCapture(CvCapture **);
extern "C" double cvGetCaptureProperty(CvCapture *,int);
extern "C" int cvSetCaptureProperty(CvCapture *,int,double);
extern "C" CvVideoWriter *cvCreateVideoWriter(char const *,int,double,CvSize);
extern "C" int cvWriteFrame(CvVideoWriter *,IplImage const *);
extern "C" void cvReleaseVideoWriter(CvVideoWriter **);
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_cvInitSystem(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    char **arg2 = (char **) 0 ;
    int result;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iO:cvInitSystem",&arg1,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_p_char,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (int)cvInitSystem(arg1,arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvNamedWindow(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"si:cvNamedWindow",&arg1,&arg2)) goto fail;
    {
        try {
            result = (int)cvNamedWindow((char const *)arg1,arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvShowImage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    CvArr *arg2 = (CvArr *) 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sO:cvShowImage",&arg1,&obj1)) goto fail;
    {
        int err = SWIG_ConvertPtr
        (
        obj1,
        (void **) &arg2, 
        SWIGTYPE_p_IplImage, 
        SWIG_POINTER_EXCEPTION
        );
        if (err == -1)
        return 0; 
    }
    {
        try {
            cvShowImage((char const *)arg1,(CvArr const *)arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvResizeWindow(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    int arg3 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sii:cvResizeWindow",&arg1,&arg2,&arg3)) goto fail;
    {
        try {
            cvResizeWindow((char const *)arg1,arg2,arg3);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvMoveWindow(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    int arg3 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sii:cvMoveWindow",&arg1,&arg2,&arg3)) goto fail;
    {
        try {
            cvMoveWindow((char const *)arg1,arg2,arg3);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvDestroyWindow(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    
    if(!PyArg_ParseTuple(args,(char *)"s:cvDestroyWindow",&arg1)) goto fail;
    {
        try {
            cvDestroyWindow((char const *)arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvDestroyAllWindows(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    
    if(!PyArg_ParseTuple(args,(char *)":cvDestroyAllWindows")) goto fail;
    {
        try {
            cvDestroyAllWindows();
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvGetWindowHandle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    void *result;
    
    if(!PyArg_ParseTuple(args,(char *)"s:cvGetWindowHandle",&arg1)) goto fail;
    {
        try {
            result = (void *)cvGetWindowHandle((char const *)arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvGetWindowName(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:cvGetWindowName",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (char *)cvGetWindowName(arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvCreateTrackbar(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    int *arg3 = (int *) 0 ;
    int arg4 ;
    CvTrackbarCallback arg5 = (CvTrackbarCallback) 0 ;
    int result;
    PyObject * obj2 = 0 ;
    PyObject * obj4 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"ssOiO:cvCreateTrackbar",&arg1,&arg2,&obj2,&arg4,&obj4)) goto fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_int,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_CvTrackbarCallback,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (int)cvCreateTrackbar((char const *)arg1,(char const *)arg2,arg3,arg4,arg5);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvGetTrackbarPos(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"ss:cvGetTrackbarPos",&arg1,&arg2)) goto fail;
    {
        try {
            result = (int)cvGetTrackbarPos((char const *)arg1,(char const *)arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvSetTrackbarPos(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    int arg3 ;
    
    if(!PyArg_ParseTuple(args,(char *)"ssi:cvSetTrackbarPos",&arg1,&arg2,&arg3)) goto fail;
    {
        try {
            cvSetTrackbarPos((char const *)arg1,(char const *)arg2,arg3);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvSetMouseCallback(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    CvMouseCallback arg2 = (CvMouseCallback) 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sO:cvSetMouseCallback",&arg1,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_CvMouseCallback,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            cvSetMouseCallback((char const *)arg1,arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvLoadImage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 = (int) 1 ;
    IplImage *result;
    
    if(!PyArg_ParseTuple(args,(char *)"s|i:cvLoadImage",&arg1,&arg2)) goto fail;
    {
        try {
            result = (IplImage *)cvLoadImage((char const *)arg1,arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IplImage, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvSaveImage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    CvArr *arg2 = (CvArr *) 0 ;
    int result;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sO:cvSaveImage",&arg1,&obj1)) goto fail;
    {
        int err = SWIG_ConvertPtr
        (
        obj1,
        (void **) &arg2, 
        SWIGTYPE_p_IplImage, 
        SWIG_POINTER_EXCEPTION
        );
        if (err == -1)
        return 0; 
    }
    {
        try {
            result = (int)cvSaveImage((char const *)arg1,(CvArr const *)arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvConvertImage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvArr *arg1 = (CvArr *) 0 ;
    CvArr *arg2 = (CvArr *) 0 ;
    int arg3 = (int) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO|i:cvConvertImage",&obj0,&obj1,&arg3)) goto fail;
    {
        int err = SWIG_ConvertPtr
        (
        obj0,
        (void **) &arg1, 
        SWIGTYPE_p_IplImage, 
        SWIG_POINTER_EXCEPTION
        );
        if (err == -1)
        return 0; 
    }
    {
        int err = SWIG_ConvertPtr
        (
        obj1,
        (void **) &arg2, 
        SWIGTYPE_p_IplImage, 
        SWIG_POINTER_EXCEPTION
        );
        if (err == -1)
        return 0; 
    }
    {
        try {
            cvConvertImage((CvArr const *)arg1,arg2,arg3);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvWaitKey(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 = (int) 0 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"|i:cvWaitKey",&arg1)) goto fail;
    {
        try {
            result = (int)cvWaitKey(arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvCaptureFromFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    CvCapture *result;
    
    if(!PyArg_ParseTuple(args,(char *)"s:cvCaptureFromFile",&arg1)) goto fail;
    {
        try {
            result = (CvCapture *)cvCaptureFromFile((char const *)arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_CvCapture, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvCaptureFromCAM(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    CvCapture *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:cvCaptureFromCAM",&arg1)) goto fail;
    {
        try {
            result = (CvCapture *)cvCaptureFromCAM(arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_CvCapture, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvGrabFrame(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvCapture *arg1 = (CvCapture *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:cvGrabFrame",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvCapture,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (int)cvGrabFrame(arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvRetrieveFrame(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvCapture *arg1 = (CvCapture *) 0 ;
    IplImage *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:cvRetrieveFrame",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvCapture,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (IplImage *)cvRetrieveFrame(arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IplImage, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvQueryFrame(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvCapture *arg1 = (CvCapture *) 0 ;
    IplImage *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:cvQueryFrame",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvCapture,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (IplImage *)cvQueryFrame(arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IplImage, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvReleaseCapture(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvCapture **arg1 = (CvCapture **) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:cvReleaseCapture",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_p_CvCapture,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            cvReleaseCapture(arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvGetCaptureProperty(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvCapture *arg1 = (CvCapture *) 0 ;
    int arg2 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:cvGetCaptureProperty",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvCapture,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (double)cvGetCaptureProperty(arg1,arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvSetCaptureProperty(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvCapture *arg1 = (CvCapture *) 0 ;
    int arg2 ;
    double arg3 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oid:cvSetCaptureProperty",&obj0,&arg2,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvCapture,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (int)cvSetCaptureProperty(arg1,arg2,arg3);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvCreateVideoWriter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    double arg3 ;
    CvSize arg4 ;
    CvVideoWriter *result;
    CvSize *argp4 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sidO:cvCreateVideoWriter",&arg1,&arg2,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &argp4, SWIGTYPE_p_CvSize,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg4 = *argp4; 
    {
        try {
            result = (CvVideoWriter *)cvCreateVideoWriter((char const *)arg1,arg2,arg3,arg4);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_CvVideoWriter, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvWriteFrame(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvVideoWriter *arg1 = (CvVideoWriter *) 0 ;
    IplImage *arg2 = (IplImage *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:cvWriteFrame",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvVideoWriter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_IplImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (int)cvWriteFrame(arg1,(IplImage const *)arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_cvReleaseVideoWriter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvVideoWriter **arg1 = (CvVideoWriter **) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:cvReleaseVideoWriter",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_p_CvVideoWriter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            cvReleaseVideoWriter(arg1);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_CvvImage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_CvvImage")) goto fail;
    {
        try {
            result = (CvvImage *)new CvvImage();
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_CvvImage, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_CvvImage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_CvvImage",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            delete arg1;
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Create(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    int arg5 = (int) 0 ;
    bool result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oiii|i:CvvImage_Create",&obj0,&arg2,&arg3,&arg4,&arg5)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (bool)(arg1)->Create(arg2,arg3,arg4,arg5);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Load(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    char *arg2 ;
    int arg3 = (int) 1 ;
    bool result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os|i:CvvImage_Load",&obj0,&arg2,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (bool)(arg1)->Load((char const *)arg2,arg3);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_LoadRect(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    char *arg2 ;
    int arg3 ;
    CvRect arg4 ;
    bool result;
    CvRect *argp4 ;
    PyObject * obj0 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OsiO:CvvImage_LoadRect",&obj0,&arg2,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &argp4, SWIGTYPE_p_CvRect,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg4 = *argp4; 
    {
        try {
            result = (bool)(arg1)->LoadRect((char const *)arg2,arg3,arg4);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Save(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    char *arg2 ;
    bool result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:CvvImage_Save",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (bool)(arg1)->Save((char const *)arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_CopyOf__SWIG_0(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    CvvImage *arg2 = 0 ;
    int arg3 = (int) -1 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO|i:CvvImage_CopyOf",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg2 == NULL) {
        PyErr_SetString(PyExc_TypeError,"null reference"); SWIG_fail; 
    }
    {
        try {
            (arg1)->CopyOf(*arg2,arg3);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_CopyOf__SWIG_1(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    IplImage *arg2 = (IplImage *) 0 ;
    int arg3 = (int) -1 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO|i:CvvImage_CopyOf",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_IplImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            (arg1)->CopyOf(arg2,arg3);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_CopyOf(PyObject *self, PyObject *args) {
    int argc;
    PyObject *argv[4];
    int ii;
    
    argc = PyObject_Length(args);
    for (ii = 0; (ii < argc) && (ii < 3); ii++) {
        argv[ii] = PyTuple_GetItem(args,ii);
    }
    if ((argc >= 2) && (argc <= 3)) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_CvvImage, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            } else {
                _v = 1;
            }
        }
        if (_v) {
            {
                void *ptr;
                if (SWIG_ConvertPtr(argv[1], (void **) &ptr, SWIGTYPE_p_CvvImage, 0) == -1) {
                    _v = 0;
                    PyErr_Clear();
                } else {
                    _v = 1;
                }
            }
            if (_v) {
                if (argc <= 2) {
                    return _wrap_CvvImage_CopyOf__SWIG_0(self,args);
                }
                {
                    _v = (PyInt_Check(argv[2]) || PyLong_Check(argv[2])) ? 1 : 0;
                }
                if (_v) {
                    return _wrap_CvvImage_CopyOf__SWIG_0(self,args);
                }
            }
        }
    }
    if ((argc >= 2) && (argc <= 3)) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_CvvImage, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            } else {
                _v = 1;
            }
        }
        if (_v) {
            {
                void *ptr;
                if (SWIG_ConvertPtr(argv[1], (void **) &ptr, SWIGTYPE_p_IplImage, 0) == -1) {
                    _v = 0;
                    PyErr_Clear();
                } else {
                    _v = 1;
                }
            }
            if (_v) {
                if (argc <= 2) {
                    return _wrap_CvvImage_CopyOf__SWIG_1(self,args);
                }
                {
                    _v = (PyInt_Check(argv[2]) || PyLong_Check(argv[2])) ? 1 : 0;
                }
                if (_v) {
                    return _wrap_CvvImage_CopyOf__SWIG_1(self,args);
                }
            }
        }
    }
    
    PyErr_SetString(PyExc_TypeError,"No matching function for overloaded 'CvvImage_CopyOf'");
    return NULL;
}


static PyObject *_wrap_CvvImage_GetImage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    IplImage *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:CvvImage_GetImage",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (IplImage *)(arg1)->GetImage();
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IplImage, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:CvvImage_Destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            (arg1)->Destroy();
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Width(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:CvvImage_Width",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (int)(arg1)->Width();
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Height(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:CvvImage_Height",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (int)(arg1)->Height();
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Bpp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:CvvImage_Bpp",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            result = (int)(arg1)->Bpp();
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Fill(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:CvvImage_Fill",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            (arg1)->Fill(arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_CvvImage_Show(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CvvImage *arg1 = (CvvImage *) 0 ;
    char *arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:CvvImage_Show",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CvvImage,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        try {
            (arg1)->Show((char const *)arg2);
        } 
        catch (...) 
        {
            return NULL;
        } 
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * CvvImage_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_CvvImage, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyMethodDef SwigMethods[] = {
	 { (char *)"cvInitSystem", _wrap_cvInitSystem, METH_VARARGS },
	 { (char *)"cvNamedWindow", _wrap_cvNamedWindow, METH_VARARGS },
	 { (char *)"cvShowImage", _wrap_cvShowImage, METH_VARARGS },
	 { (char *)"cvResizeWindow", _wrap_cvResizeWindow, METH_VARARGS },
	 { (char *)"cvMoveWindow", _wrap_cvMoveWindow, METH_VARARGS },
	 { (char *)"cvDestroyWindow", _wrap_cvDestroyWindow, METH_VARARGS },
	 { (char *)"cvDestroyAllWindows", _wrap_cvDestroyAllWindows, METH_VARARGS },
	 { (char *)"cvGetWindowHandle", _wrap_cvGetWindowHandle, METH_VARARGS },
	 { (char *)"cvGetWindowName", _wrap_cvGetWindowName, METH_VARARGS },
	 { (char *)"cvCreateTrackbar", _wrap_cvCreateTrackbar, METH_VARARGS },
	 { (char *)"cvGetTrackbarPos", _wrap_cvGetTrackbarPos, METH_VARARGS },
	 { (char *)"cvSetTrackbarPos", _wrap_cvSetTrackbarPos, METH_VARARGS },
	 { (char *)"cvSetMouseCallback", _wrap_cvSetMouseCallback, METH_VARARGS },
	 { (char *)"cvLoadImage", _wrap_cvLoadImage, METH_VARARGS },
	 { (char *)"cvSaveImage", _wrap_cvSaveImage, METH_VARARGS },
	 { (char *)"cvConvertImage", _wrap_cvConvertImage, METH_VARARGS },
	 { (char *)"cvWaitKey", _wrap_cvWaitKey, METH_VARARGS },
	 { (char *)"cvCaptureFromFile", _wrap_cvCaptureFromFile, METH_VARARGS },
	 { (char *)"cvCaptureFromCAM", _wrap_cvCaptureFromCAM, METH_VARARGS },
	 { (char *)"cvGrabFrame", _wrap_cvGrabFrame, METH_VARARGS },
	 { (char *)"cvRetrieveFrame", _wrap_cvRetrieveFrame, METH_VARARGS },
	 { (char *)"cvQueryFrame", _wrap_cvQueryFrame, METH_VARARGS },
	 { (char *)"cvReleaseCapture", _wrap_cvReleaseCapture, METH_VARARGS },
	 { (char *)"cvGetCaptureProperty", _wrap_cvGetCaptureProperty, METH_VARARGS },
	 { (char *)"cvSetCaptureProperty", _wrap_cvSetCaptureProperty, METH_VARARGS },
	 { (char *)"cvCreateVideoWriter", _wrap_cvCreateVideoWriter, METH_VARARGS },
	 { (char *)"cvWriteFrame", _wrap_cvWriteFrame, METH_VARARGS },
	 { (char *)"cvReleaseVideoWriter", _wrap_cvReleaseVideoWriter, METH_VARARGS },
	 { (char *)"new_CvvImage", _wrap_new_CvvImage, METH_VARARGS },
	 { (char *)"delete_CvvImage", _wrap_delete_CvvImage, METH_VARARGS },
	 { (char *)"CvvImage_Create", _wrap_CvvImage_Create, METH_VARARGS },
	 { (char *)"CvvImage_Load", _wrap_CvvImage_Load, METH_VARARGS },
	 { (char *)"CvvImage_LoadRect", _wrap_CvvImage_LoadRect, METH_VARARGS },
	 { (char *)"CvvImage_Save", _wrap_CvvImage_Save, METH_VARARGS },
	 { (char *)"CvvImage_CopyOf", _wrap_CvvImage_CopyOf, METH_VARARGS },
	 { (char *)"CvvImage_GetImage", _wrap_CvvImage_GetImage, METH_VARARGS },
	 { (char *)"CvvImage_Destroy", _wrap_CvvImage_Destroy, METH_VARARGS },
	 { (char *)"CvvImage_Width", _wrap_CvvImage_Width, METH_VARARGS },
	 { (char *)"CvvImage_Height", _wrap_CvvImage_Height, METH_VARARGS },
	 { (char *)"CvvImage_Bpp", _wrap_CvvImage_Bpp, METH_VARARGS },
	 { (char *)"CvvImage_Fill", _wrap_CvvImage_Fill, METH_VARARGS },
	 { (char *)"CvvImage_Show", _wrap_CvvImage_Show, METH_VARARGS },
	 { (char *)"CvvImage_swigregister", CvvImage_swigregister, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_p_CvCapture[] = {{"_p_p_CvCapture", 0, "CvCapture **", 0},{"_p_p_CvCapture"},{0}};
static swig_type_info _swigt__p_CvCapture[] = {{"_p_CvCapture", 0, "CvCapture *", 0},{"_p_CvCapture"},{0}};
static swig_type_info _swigt__p_IplImage[] = {{"_p_IplImage", 0, "IplImage *", 0},{"_p_IplImage"},{0}};
static swig_type_info _swigt__p_CvvImage[] = {{"_p_CvvImage", 0, "CvvImage *", 0},{"_p_CvvImage"},{0}};
static swig_type_info _swigt__CvMouseCallback[] = {{"_CvMouseCallback", 0, "CvMouseCallback", 0},{"_CvMouseCallback"},{0}};
static swig_type_info _swigt__CvTrackbarCallback[] = {{"_CvTrackbarCallback", 0, "CvTrackbarCallback", 0},{"_CvTrackbarCallback"},{0}};
static swig_type_info _swigt__p_void[] = {{"_p_void", 0, "void *", 0},{"_p_void"},{0}};
static swig_type_info _swigt__p_CvSize[] = {{"_p_CvSize", 0, "CvSize *", 0},{"_p_CvSize"},{0}};
static swig_type_info _swigt__p_p_char[] = {{"_p_p_char", 0, "char **", 0},{"_p_p_char"},{0}};
static swig_type_info _swigt__p_p_CvVideoWriter[] = {{"_p_p_CvVideoWriter", 0, "CvVideoWriter **", 0},{"_p_p_CvVideoWriter"},{0}};
static swig_type_info _swigt__p_CvVideoWriter[] = {{"_p_CvVideoWriter", 0, "CvVideoWriter *", 0},{"_p_CvVideoWriter"},{0}};
static swig_type_info _swigt__p_CvRect[] = {{"_p_CvRect", 0, "CvRect *", 0},{"_p_CvRect"},{0}};
static swig_type_info _swigt__p_CvArr[] = {{"_p_CvArr", 0, "CvArr *", 0},{"_p_CvArr"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *", 0},{"_p_int"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_p_CvCapture, 
_swigt__p_CvCapture, 
_swigt__p_IplImage, 
_swigt__p_CvvImage, 
_swigt__CvMouseCallback, 
_swigt__CvTrackbarCallback, 
_swigt__p_void, 
_swigt__p_CvSize, 
_swigt__p_p_char, 
_swigt__p_p_CvVideoWriter, 
_swigt__p_CvVideoWriter, 
_swigt__p_CvRect, 
_swigt__p_CvArr, 
_swigt__p_int, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_INT,     (char *)"CV_WINDOW_AUTOSIZE", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_MOUSEMOVE", (long) 0, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_LBUTTONDOWN", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_RBUTTONDOWN", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_MBUTTONDOWN", (long) 3, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_LBUTTONUP", (long) 4, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_RBUTTONUP", (long) 5, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_MBUTTONUP", (long) 6, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_LBUTTONDBLCLK", (long) 7, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_RBUTTONDBLCLK", (long) 8, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_MBUTTONDBLCLK", (long) 9, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_FLAG_LBUTTON", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_FLAG_RBUTTON", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_FLAG_MBUTTON", (long) 4, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_FLAG_CTRLKEY", (long) 8, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_FLAG_SHIFTKEY", (long) 16, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_EVENT_FLAG_ALTKEY", (long) 32, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CVTIMG_FLIP", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CVTIMG_SWAP_RB", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_ANY", (long) 0, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_MIL", (long) 100, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_VFW", (long) 200, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_V4L", (long) 200, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_V4L2", (long) 200, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_FIREWARE", (long) 300, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_IEEE1394", (long) 300, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_DC1394", (long) 300, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_CMU1394", (long) 300, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_PROP_POS_MSEC", (long) 0, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_PROP_POS_FRAMES", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_PROP_POS_AVI_RATIO", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_PROP_FRAME_WIDTH", (long) 3, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_PROP_FRAME_HEIGHT", (long) 4, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_PROP_FPS", (long) 5, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_PROP_FOURCC", (long) 6, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"CV_CAP_PROP_FRAME_COUNT", (long) 7, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"HG_AUTOSIZE", (long) 1, 0, 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

