createsamples3d: createsamples3d.cpp createsamplesfromvideo.cpp calibration.cpp calibration.h createsamplesfromvideo.h createsamples3d.h
	g++ -o createsamples3d -g createsamples3d.cpp createsamplesfromvideo.cpp calibration.cpp -lml -lcv -lcxcore -lcvaux -lhighgui
