#!/bin/bash

tput clear

#cd .. && make && cd -
mkdir -p _build/html/python

if false
then
  rm -f *.rst
  svn up
  cp index-c.rst.copy index.rst
  TEXINPUTS=../: python renderer.py c # > a || exit
  TEXINPUTS=$PWD: sphinx-build -b html -D 'html_title=OpenCV 2.0 C Reference' -d _build/doctrees . _build/html
fi

if false
then
  rm -f *.rst
  svn up
  cp index-py.rst.copy index.rst
  TEXINPUTS=../: python renderer.py py > a || exit
  TEXINPUTS=$PWD: sphinx-build -b html -D 'highlight_language=python' -D 'html_title=OpenCV 2.0 Python Reference' -d _build/doctrees . _build/html/python
fi

if true
then
  rm -f *.rst
  svn up
  cp index-cpp.rst.copy index.rst
  TEXINPUTS=../: python renderer.py cpp > a || exit
  TEXINPUTS=$PWD: sphinx-build -b html -D 'html_title=OpenCV 2.0 C++ Reference' -d _build/doctrees . _build/html/cpp
fi
