#!/bin/bash

mkdir -p c cpp py
tput clear
python latex.py ../online-opencv.tex || exit

for D in c cpp py
do
  mkdir -p $D
  cp conf.py $D
  TEXINPUTS=$PWD: sphinx-build -w $D/sphinx.errors -D "lang=$D" -b html -d _build/doctrees/$D $D _build/html/$D
done
