#!/bin/bash

tput clear
python latex.py ../online-opencv.tex || exit

TEXINPUTS=$PWD: sphinx-build -w sphinx.errors -b html -D 'highlight_language=python' -D 'html_title=OpenCV 2.0 Python Reference' -d _build/doctrees . _build/html/python
